<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="RTExcel.aspx.cs" Inherits="GeoSI.Website.Modules.RapportTrajet.RTExcel" %>


<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <title></title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6/jquery.min.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js" type="text/javascript"></script>
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="Stylesheet" type="text/css" />
    <script type="text/javascript">
        $(function () {

            $("[id$=startdate]").datepicker({
                showOn: 'button',
                buttonImageOnly: true,
                buttonImage: '../../Ressources/Images/arrow.png'

            });
            $.datepicker.setDefaults(
  $.extend(
    { 'dateFormat': 'dd/mm/yy' },
    $.datepicker.regional['fr']
  )
);
        });

        $(function () {
            $("[id$=enddate]").datepicker({
                showOn: 'button',
                buttonImageOnly: true,
                buttonImage: '../../Ressources/Images/arrow.png'
            });
            $.datepicker.setDefaults(
 $.extend(
   { 'dateFormat': 'dd/mm/yy' },
   $.datepicker.regional['fr']
 )
);
        });
    </script>
</head>
<body>
   <form id="form1" runat="server">
<div id="divGridView">
    
    <asp:gridview id="GridView1" runat="server" enableviewstate="False" width="100%" BorderWidth="1"
        cellpadding="4" forecolor="#333333" gridlines="None" autogeneratecolumns="false"
        datakeynames="vehiculeConfid" autogeneratedeletebutton="false" EmptyDataText="No records found" hidden="true" >
            <HeaderStyle BackColor="#507CD1" HorizontalAlign="Left" Font-Bold="True" ForeColor="White" />
            <Columns>
                <asp:BoundField DataField="vehiculeConfid" HeaderText="vehiculeConfid" />
               
                <asp:BoundField HeaderText="vehiculeid" DataField="vehiculeid" />
                                <asp:BoundField HeaderText="vitesseMax" DataField="vitesseMax" />

             
            </Columns>
        </asp:gridview>
<div id="content">
        Date debut  <asp:TextBox ID="startdate" class="field" runat="server"></asp:TextBox> 
        Date Fin <asp:TextBox ID="enddate" class="field" runat="server"></asp:TextBox>
    </div>

        <asp:Label ID="lblMessage" runat="server" EnableViewState="false" />
       
            <asp:Button ID="Button5" runat="server" Text="excel" OnClick="Gen"  />
    

</div>
</form>
</body>
</html>
